# Node CircleCI 2.0 configuration file to Something
version: 2
jobs:

  # TEST JOB
  # installing dependencies, testing and building assets
  test:
    docker:
      - image: circleci/node:8.9.1

    steps:
      - checkout                       # get the files from the repo (why would you ever not want the files????)
      - run: rm -rf node_modules       # delete node_modules to bust caching
      - run: npm install               # duh
      - run: npm test                  # testing first!
      - run: npm run build             # required build step
      - run: rm -rf node_modules       # delete node_modules folder again to not push it to cf


# OUR WORKFLOW
# this is where we orchestrate our jobs
workflows:
  version: 2
  testing:
    jobs:

      - test:               # run test
          filters:
            branches:
              only: develop # and only in the `develop` branch

      - test:               # run test
          filters:
            branches:
              only: master  # and only in the `master` branch
